
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "^1.19.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "^1.2.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.3.0"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "^2.2.6"
